version: "3.9"
services:
  frontend:
    container_name: react-gmap
    image: react-gmap:1.0
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"